In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import sys

In [2]:
# Dataset is entered
dataset_train = pd.read_csv('Google_Stock_Price_Train.csv')
# Particular rows and colums are read
training_set = dataset_train.iloc[:,1:2].values

In [3]:
np.set_printoptions(threshold=sys.maxsize,precision=2)
# Printing Training set for test
print(training_set)

[[325.25]
 [331.27]
 [329.83]
 [328.34]
 [322.04]
 [313.7 ]
 [310.59]
 [314.43]
 [311.96]
 [314.81]
 [312.14]
 [319.3 ]
 [294.16]
 [291.91]
 [292.07]
 [287.68]
 [284.92]
 [284.32]
 [287.95]
 [290.41]
 [291.38]
 [291.34]
 [294.23]
 [296.39]
 [302.44]
 [303.18]
 [304.87]
 [302.81]
 [304.11]
 [304.63]
 [305.32]
 [300.28]
 [301.36]
 [300.81]
 [304.84]
 [302.37]
 [302.54]
 [302.16]
 [303.86]
 [308.14]
 [309.97]
 [309.84]
 [309.06]
 [302.89]
 [303.39]
 [303.88]
 [302.84]
 [298.88]
 [303.24]
 [306.35]
 [307.15]
 [309.29]
 [310.4 ]
 [314.28]
 [316.12]
 [318.06]
 [322.09]
 [321.3 ]
 [322.31]
 [324.8 ]
 [325.5 ]
 [324.66]
 [319.19]
 [321.5 ]
 [318.03]
 [314.94]
 [313.07]
 [315.58]
 [315.8 ]
 [319.98]
 [322.57]
 [310.34]
 [303.14]
 [302.89]
 [301.71]
 [301.  ]
 [295.34]
 [298.  ]
 [300.87]
 [304.31]
 [306.36]
 [305.35]
 [300.77]
 [299.48]
 [303.67]
 [301.83]
 [296.39]
 [301.63]
 [302.28]
 [305.34]
 [304.04]
 [299.27]
 [301.54]
 [307.83]
 [315.73]
 [311.38]
 [299.13]
 [305.57]
 [299.7 ]
 [303.44]


In [4]:
from sklearn.preprocessing import MinMaxScaler

# Create an instance of the MinMaxScaler
scaler = MinMaxScaler(feature_range=(0, 1))

# Reshape the training_set if needed
training_set = training_set.reshape(-1, 1)

# Scale the training data
training_set_scaled = scaler.fit_transform(training_set)


In [5]:
# In summary, this code snippet creates input sequences (X_train) and 
#  corresponding target values (y_train) by sliding a window over the 
#  training_set_scaled array. These sequences can be used to train a 
#  time series forecasting model, such as a recurrent neural network (RNN) 
#  or a convolutional neural network (CNN), to predict the next value in 
#  the time series based on the previous 60 values.

# Creating a data structure with 60 timesteps and 1 output

X_train = []
y_train = []

for i in range(60, 1258):
    X_train.append(training_set_scaled[i-60:i, 0])
    y_train.append(training_set_scaled[i, 0])

# Convert the lists to numpy arrays
X_train = np.array(X_train)
y_train = np.array(y_train)

In [6]:
print(X_train)

[[8.58e-02 9.70e-02 9.43e-02 9.16e-02 7.98e-02 6.43e-02 5.85e-02 6.57e-02
  6.11e-02 6.64e-02 6.14e-02 7.47e-02 2.80e-02 2.38e-02 2.41e-02 1.59e-02
  1.08e-02 9.67e-03 1.64e-02 2.10e-02 2.28e-02 2.27e-02 2.81e-02 3.21e-02
  4.34e-02 4.48e-02 4.79e-02 4.41e-02 4.65e-02 4.75e-02 4.87e-02 3.94e-02
  4.14e-02 4.03e-02 4.78e-02 4.33e-02 4.36e-02 4.29e-02 4.60e-02 5.40e-02
  5.74e-02 5.71e-02 5.57e-02 4.42e-02 4.51e-02 4.61e-02 4.41e-02 3.68e-02
  4.49e-02 5.07e-02 5.21e-02 5.61e-02 5.82e-02 6.54e-02 6.88e-02 7.24e-02
  7.99e-02 7.85e-02 8.03e-02 8.50e-02]
 [9.70e-02 9.43e-02 9.16e-02 7.98e-02 6.43e-02 5.85e-02 6.57e-02 6.11e-02
  6.64e-02 6.14e-02 7.47e-02 2.80e-02 2.38e-02 2.41e-02 1.59e-02 1.08e-02
  9.67e-03 1.64e-02 2.10e-02 2.28e-02 2.27e-02 2.81e-02 3.21e-02 4.34e-02
  4.48e-02 4.79e-02 4.41e-02 4.65e-02 4.75e-02 4.87e-02 3.94e-02 4.14e-02
  4.03e-02 4.78e-02 4.33e-02 4.36e-02 4.29e-02 4.60e-02 5.40e-02 5.74e-02
  5.71e-02 5.57e-02 4.42e-02 4.51e-02 4.61e-02 4.41e-02 3.68e-02 4.49e-02

In [7]:
y_train


array([8.63e-02, 8.47e-02, 7.45e-02, 7.88e-02, 7.24e-02, 6.66e-02,
       6.32e-02, 6.78e-02, 6.82e-02, 7.60e-02, 8.08e-02, 5.81e-02,
       4.47e-02, 4.42e-02, 4.20e-02, 4.07e-02, 3.02e-02, 3.51e-02,
       4.05e-02, 4.69e-02, 5.07e-02, 4.88e-02, 4.03e-02, 3.79e-02,
       4.57e-02, 4.22e-02, 3.21e-02, 4.19e-02, 4.31e-02, 4.88e-02,
       4.64e-02, 3.75e-02, 4.17e-02, 5.34e-02, 6.81e-02, 6.00e-02,
       3.72e-02, 4.92e-02, 3.83e-02, 4.52e-02, 3.77e-02, 3.29e-02,
       2.58e-02, 2.63e-02, 1.06e-02, 9.17e-03, 1.40e-02, 1.50e-02,
       2.53e-02, 1.44e-02, 2.21e-02, 8.74e-03, 1.28e-03, 8.93e-04,
       0.00e+00, 2.12e-03, 1.23e-02, 1.80e-02, 1.81e-02, 7.11e-03,
       6.49e-03, 2.25e-03, 6.83e-03, 5.15e-03, 1.36e-02, 1.99e-02,
       1.82e-02, 2.63e-02, 2.98e-02, 2.28e-02, 2.77e-02, 1.48e-02,
       6.29e-03, 1.10e-02, 1.49e-02, 1.68e-02, 1.54e-02, 2.39e-02,
       4.49e-02, 3.72e-02, 5.07e-02, 4.45e-02, 5.07e-02, 5.43e-02,
       7.02e-02, 6.30e-02, 7.13e-02, 6.04e-02, 7.38e-02, 7.35e

In [8]:
# We can add some more indicators after reshaping it
X_train = np.reshape(X_train,(X_train.shape[0],X_train.shape[1],1))
#  This reshaping is often required when working with RNNs or CNNs because
#   these models expect input data in a specific shape, typically in the 
#   form of (batch size, sequence length, number of features). In this case, 
#   the reshaping prepares the data to be fed into a model that expects input
#   sequences with a length of 60 and a single feature value at each time step.
X_train.shape

(1198, 60, 1)

In [9]:
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import LSTM
from keras.layers import Dropout

In [10]:
regressor = Sequential()

In [11]:
regressor.add(LSTM(units = 50 , return_sequences = True , input_shape = (X_train.shape[1],1)))
regressor.add(Dropout(0.2))
# The line of code regressor.add(Dropout(0.2)) adds a Dropout layer to the neural network 
#   model regressor. Here, 0.2 represents the fraction of input units to drop during
#   training, which is set to 20% in this case.

In [12]:
regressor.add(LSTM(units = 50 , return_sequences = True))
regressor.add(Dropout(0.2))

In [13]:
regressor.add(LSTM(units = 50 , return_sequences = True))
regressor.add(Dropout(0.2))

In [14]:
regressor.add(LSTM(units = 50))
regressor.add(Dropout(0.2)) 

In [15]:
regressor.add(Dense(units = 1))

In [16]:
# We can use RMSprop also by checking which is giving more proper result
regressor.compile(optimizer = 'adam' , loss = 'mean_squared_error')

In [17]:
# Fitting the RNN to training set
regressor.fit(X_train, y_train, epochs = 100 , batch_size = 32)

Epoch 1/100
38/38 [==============================] - 15s 132ms/step - loss: 0.0493
Epoch 2/100
38/38 [==============================] - 6s 167ms/step - loss: 0.0061
Epoch 3/100
38/38 [==============================] - 5s 132ms/step - loss: 0.0050
Epoch 4/100
38/38 [==============================] - 6s 164ms/step - loss: 0.0059
Epoch 5/100
38/38 [==============================] - 5s 133ms/step - loss: 0.0049
Epoch 6/100
38/38 [==============================] - 5s 142ms/step - loss: 0.0046
Epoch 7/100
38/38 [==============================] - 6s 153ms/step - loss: 0.0048
Epoch 8/100
38/38 [==============================] - 5s 132ms/step - loss: 0.0050
Epoch 9/100
38/38 [==============================] - 6s 168ms/step - loss: 0.0051
Epoch 10/100
38/38 [==============================] - 5s 136ms/step - loss: 0.0045
Epoch 11/100
38/38 [==============================] - 6s 171ms/step - loss: 0.0043
Epoch 12/100
38/38 [==============================] - 5s 134ms/step - loss: 0.0040
Epoch 13/100

In [18]:
dataset_test = pd.read_csv('Google_Stock_Price_Test.csv')
real_stock_price = dataset_test.iloc[:,1:2].values

In [19]:
dataset_total = pd.concat((dataset_train['Open'], dataset_test['Open']), axis = 0)
inputs = dataset_total[len(dataset_total) - len(dataset_test) - 60:].values
inputs = inputs.reshape(-1,1)
inputs = scaler.transform(inputs)
X_test = []
for i in range(60, 80):
    X_test.append(inputs[i-60:i, 0])
X_test = np.array(X_test)
X_test = np.reshape(X_test, (X_test.shape[0], X_test.shape[1], 1))
predicted_stock_price = regressor.predict(X_test)
predicted_stock_price = scaler.inverse_transform(predicted_stock_price)

1/1 [==============================] - 2s 2s/step


In [20]:
real_stock_price,predicted_stock_price

(array([[778.81],
        [788.36],
        [786.08],
        [795.26],
        [806.4 ],
        [807.86],
        [805.  ],
        [807.14],
        [807.48],
        [807.08],
        [805.81],
        [805.12],
        [806.91],
        [807.25],
        [822.3 ],
        [829.62],
        [837.81],
        [834.71],
        [814.66],
        [796.86]]),
 array([[785.07],
        [782.17],
        [781.63],
        [782.53],
        [785.43],
        [790.86],
        [796.37],
        [799.23],
        [799.96],
        [799.71],
        [799.29],
        [798.89],
        [798.63],
        [799.03],
        [799.93],
        [803.96],
        [810.47],
        [817.87],
        [822.52],
        [819.74]], dtype=float32))